version: 2
jobs:
  build:
    docker:
      - image: python
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: mypy src
      - run: pytest
      - run: python3 src/main.py
